Mar-18 21:52:14.424 [main] DEBUG nextflow.cli.Launcher - $> nextflow analyze_pulses.nf --metadata data/hangman_signals.csv -c data/params_hangman_pan.config -with-conda true
Mar-18 21:52:14.498 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 22.10.3
Mar-18 21:52:14.506 [main] DEBUG nextflow.plugin.PluginsFacade - Setting up plugin manager > mode=prod; embedded=false; plugins-dir=/Users/oakley/.nextflow/plugins; core-plugins: nf-amazon@1.11.1,nf-azure@0.14.2,nf-codecommit@0.1.2,nf-console@1.0.4,nf-ga4gh@1.0.4,nf-google@1.4.5,nf-tower@1.5.6,nf-wave@0.5.2
Mar-18 21:52:14.510 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
Mar-18 21:52:14.510 [main] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
Mar-18 21:52:14.511 [main] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.4.1 in 'deployment' mode
Mar-18 21:52:14.516 [main] INFO  org.pf4j.AbstractPluginManager - No plugins
Mar-18 21:52:14.525 [main] DEBUG nextflow.config.ConfigBuilder - User config file: /Users/oakley/Documents/GitHub/WALL-E/nextflow/data/params_hangman_pan.config
Mar-18 21:52:14.525 [main] DEBUG nextflow.config.ConfigBuilder - Parsing config file: /Users/oakley/Documents/GitHub/WALL-E/nextflow/data/params_hangman_pan.config
Mar-18 21:52:14.533 [main] DEBUG nextflow.config.ConfigBuilder - Applying config profile: `standard`
Mar-18 21:52:14.774 [main] DEBUG nextflow.cli.CmdRun - Applied DSL=2 from script declararion
Mar-18 21:52:14.782 [main] INFO  nextflow.cli.CmdRun - Launching `analyze_pulses.nf` [voluminous_allen] DSL2 - revision: 7311b71f9e
Mar-18 21:52:14.782 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins default=[]
Mar-18 21:52:14.782 [main] DEBUG nextflow.plugin.PluginsFacade - Plugins resolved requirement=[]
Mar-18 21:52:14.786 [main] DEBUG nextflow.secret.LocalSecretsProvider - Secrets store: /Users/oakley/.nextflow/secrets/store.json
Mar-18 21:52:14.787 [main] DEBUG nextflow.secret.SecretsLoader - Discovered secrets providers: [nextflow.secret.LocalSecretsProvider@49faf066] - activable => nextflow.secret.LocalSecretsProvider@49faf066
Mar-18 21:52:14.813 [main] DEBUG nextflow.Session - Session UUID: 1ab73328-35e4-48ca-b869-cad822bd725d
Mar-18 21:52:14.814 [main] DEBUG nextflow.Session - Run name: voluminous_allen
Mar-18 21:52:14.814 [main] DEBUG nextflow.Session - Executor pool size: 10
Mar-18 21:52:14.818 [main] DEBUG nextflow.util.ThreadPoolBuilder - Creating thread pool 'FileTransfer' minSize=10; maxSize=30; workQueue=LinkedBlockingQueue[10000]; allowCoreThreadTimeout=false
Mar-18 21:52:14.829 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 22.10.3 build 5834
  Created: 21-11-2022 21:37 UTC (13:37 PDT)
  System: Mac OS X 13.2.1
  Runtime: Groovy 3.0.13 on OpenJDK 64-Bit Server VM 17.0.3+7-LTS
  Encoding: UTF-8 (UTF-8)
  Process: 7775@gamera.eemb.ucsb.edu [128.111.226.15]
  CPUs: 10 - Mem: 32 GB (2.3 GB) - Swap: 0 (0)
Mar-18 21:52:14.835 [main] DEBUG nextflow.Session - Work-dir: /Users/oakley/Documents/GitHub/WALL-E/nextflow/work [Mac OS X]
Mar-18 21:52:14.850 [main] DEBUG nextflow.executor.ExecutorFactory - Extension executors providers=[]
Mar-18 21:52:14.854 [main] DEBUG nextflow.Session - Observer factory: DefaultObserverFactory
Mar-18 21:52:14.867 [main] DEBUG nextflow.cache.CacheFactory - Using Nextflow cache factory: nextflow.cache.DefaultCacheFactory
Mar-18 21:52:14.870 [main] DEBUG nextflow.util.CustomThreadPool - Creating default thread pool > poolSize: 11; maxThreads: 1000
Mar-18 21:52:14.899 [main] DEBUG nextflow.Session - Session start
Mar-18 21:52:15.169 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Mar-18 21:52:15.228 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.229 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.231 [main] DEBUG nextflow.executor.Executor - [warm up] executor > local
Mar-18 21:52:15.233 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=10; memory=32 GB; capacity=10; pollInterval=100ms; dumpInterval=5m
Mar-18 21:52:15.261 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.261 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.263 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.263 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.266 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.266 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.268 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.268 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.269 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.269 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.270 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.271 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.272 [main] DEBUG nextflow.executor.ExecutorFactory - << taskConfig executor: null
Mar-18 21:52:15.272 [main] DEBUG nextflow.executor.ExecutorFactory - >> processorType: 'local'
Mar-18 21:52:15.274 [main] DEBUG nextflow.Session - Workflow process names [dsl2]: visualize_coordinates, find_contours, rectify, visualize, visualize_segments, undistort, parallax_depth, segment_contours
Mar-18 21:52:15.274 [main] DEBUG nextflow.Session - Igniting dataflow network (9)
Mar-18 21:52:15.276 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > undistort
Mar-18 21:52:15.276 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > rectify
Mar-18 21:52:15.276 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > find_contours
Mar-18 21:52:15.277 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > segment_contours
Mar-18 21:52:15.277 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > parallax_depth
Mar-18 21:52:15.277 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > visualize
Mar-18 21:52:15.277 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > visualize_segments
Mar-18 21:52:15.277 [main] DEBUG nextflow.processor.TaskProcessor - Starting process > visualize_coordinates
Mar-18 21:52:15.277 [main] DEBUG nextflow.script.ScriptRunner - > Awaiting termination 
Mar-18 21:52:15.277 [main] DEBUG nextflow.Session - Session await
Mar-18 21:52:15.315 [Actor Thread 9] DEBUG nextflow.conda.CondaCache - conda found local env for environment=conda-forge::opencv=4.5.0 conda-forge::numpy=1.19.4; path=/Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-c185fe4baf89519afaa336aee909e5f9
Mar-18 21:52:15.344 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-18 21:52:15.345 [Task submitter] INFO  nextflow.Session - [74/edf2e4] Submitted process > undistort (1)
Mar-18 21:52:18.394 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: undistort (1); status: COMPLETED; exit: 0; error: -; workDir: /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/74/edf2e4c468ecbfdfc58762e1c106c8]
Mar-18 21:52:18.424 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-18 21:52:18.424 [Task submitter] INFO  nextflow.Session - [ed/421b88] Submitted process > rectify (1)
Mar-18 21:52:25.129 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 2; name: rectify (1); status: COMPLETED; exit: 0; error: -; workDir: /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/ed/421b88135dd46af08681fb5bb12b76]
Mar-18 21:52:25.145 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Mar-18 21:52:25.145 [Task submitter] INFO  nextflow.Session - [1f/2a1744] Submitted process > find_contours (1)
Mar-18 21:52:26.622 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 3; name: find_contours (1); status: COMPLETED; exit: 0; error: -; workDir: /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/1f/2a174450fe5ce6325e64a1eca83844]
Mar-18 21:52:26.630 [Actor Thread 5] INFO  nextflow.conda.CondaCache - Creating env using conda: conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy [cache /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-65db48aa4fd1615ada9938d6c7e93a97]
Mar-18 21:52:26.663 [Actor Thread 4] INFO  nextflow.conda.CondaCache - Creating env using conda: conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy conda-forge::scipy=1.6.0 [cache /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-eff40dfaeef0312a153113b3270a5210]
Mar-18 21:52:38.025 [Actor Thread 6] ERROR nextflow.processor.TaskProcessor - Error executing process > 'segment_contours (1)'

Caused by:
  Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-eff40dfaeef0312a153113b3270a5210 conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy conda-forge::scipy=1.6.0
  status : 1
  message:
    InvalidArchiveError('Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/pillow-9.4.0-py39hfc21214_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: File is not a zip file')
    InvalidArchiveError("Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2'")


java.lang.IllegalStateException: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-eff40dfaeef0312a153113b3270a5210 conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy conda-forge::scipy=1.6.0
  status : 1
  message:
    InvalidArchiveError('Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/pillow-9.4.0-py39hfc21214_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: File is not a zip file')
    InvalidArchiveError("Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2'")

	at nextflow.conda.CondaCache.getCachePathFor(CondaCache.groovy:364)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite.invoke(PogoMetaMethodSite.java:170)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at nextflow.processor.TaskRun.memoizedMethodPriv$getCondaEnv(TaskRun.groovy:585)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:176)
	at nextflow.processor.TaskRun$_closure2.doCall(TaskRun.groovy)
	at nextflow.processor.TaskRun$_closure2.doCall(TaskRun.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.lambda$call$0(Memoize.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:137)
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:113)
	at org.codehaus.groovy.runtime.memoize.Memoize$MemoizeFunction.call(Memoize.java:136)
	at groovy.lang.Closure.call(Closure.java:406)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at nextflow.processor.TaskRun.getCondaEnv(TaskRun.groovy)
	at nextflow.processor.TaskRun$getCondaEnv$5.call(Unknown Source)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:2040)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:61)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:599)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:53)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-eff40dfaeef0312a153113b3270a5210 conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy conda-forge::scipy=1.6.0
  status : 1
  message:
    InvalidArchiveError('Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/pillow-9.4.0-py39hfc21214_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: File is not a zip file')
    InvalidArchiveError("Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2'")

	at nextflow.conda.CondaCache.runCommand(CondaCache.groovy:313)
	at nextflow.conda.CondaCache.createLocalCondaEnv0(CondaCache.groovy:285)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.doCall(CondaCache.groovy:247)
	at nextflow.conda.CondaCache$_createLocalCondaEnv_closure1.call(CondaCache.groovy)
	at nextflow.file.FileMutex.lock(FileMutex.groovy:107)
	at nextflow.conda.CondaCache.createLocalCondaEnv(CondaCache.groovy:247)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1268)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1029)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:1012)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethodSafe(InvokerHelper.java:101)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure2.doCall(CondaCache.groovy:341)
	at nextflow.conda.CondaCache$_getLazyImagePath_closure2.call(CondaCache.groovy)
	at groovyx.gpars.dataflow.LazyDataflowVariable$1.run(LazyDataflowVariable.java:70)
	... 3 common frames omitted
Mar-18 21:52:38.028 [Actor Thread 6] DEBUG nextflow.Session - Session aborted -- Cause: java.lang.IllegalStateException: Failed to create Conda environment
  command: conda create --mkdir --yes --quiet --prefix /Users/oakley/Documents/GitHub/WALL-E/nextflow/work/conda/env-eff40dfaeef0312a153113b3270a5210 conda-forge::matplotlib=3.3.3 conda-forge::pandas conda-forge::seaborn conda-forge::numpy conda-forge::scipy=1.6.0
  status : 1
  message:
    InvalidArchiveError('Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/pillow-9.4.0-py39hfc21214_2.conda.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: File is not a zip file')
    InvalidArchiveError("Error with archive /opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message was:\n\nfailed with error: [Errno 2] No such file or directory: '/opt/homebrew/Caskroom/miniforge/base/pkgs/scipy-1.6.0-py39h73ea49b_0.tar.bz2'")

Mar-18 21:52:38.034 [Actor Thread 6] DEBUG nextflow.Session - The following nodes are still active:
[process] segment_contours
  status=ACTIVE
  port 0: (queue) closed; channel: -
  port 1: (cntrl) -     ; channel: $

[process] parallax_depth
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] visualize
  status=ACTIVE
  port 0: (queue) closed; channel: -
  port 1: (cntrl) -     ; channel: $

[process] visualize_segments
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

[process] visualize_coordinates
  status=ACTIVE
  port 0: (queue) OPEN  ; channel: -
  port 1: (cntrl) -     ; channel: $

Mar-18 21:52:38.035 [main] DEBUG nextflow.Session - Session await > all processes finished
Mar-18 21:52:38.035 [main] DEBUG nextflow.Session - Session await > all barriers passed
Mar-18 21:52:38.038 [main] DEBUG nextflow.trace.WorkflowStatsObserver - Workflow completed > WorkflowStats[succeededCount=3; failedCount=0; ignoredCount=0; cachedCount=0; pendingCount=0; submittedCount=0; runningCount=0; retriesCount=0; abortedCount=0; succeedDuration=11s; failedDuration=0ms; cachedDuration=0ms;loadCpus=0; loadMemory=0; peakRunning=1; peakCpus=1; peakMemory=0; ]
Mar-18 21:52:38.242 [main] DEBUG nextflow.cache.CacheDB - Closing CacheDB done
Mar-18 21:52:38.253 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
